language: ruby
rvm:
 - 2.5.0

before_install:
  - "gem update --system"
  - "gem install bundler"
  - sudo apt-get -qq update
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libxerces-c3.1 libxerces-c-dev
  - echo "SESHAT_PATH=/home/travis/build/jusleg/seshat-web/seshat" > 'web/.env'

jobs:
  include:
    - stage: Compile test seshat ⏳
      script: cd seshat; make
    - stage: Testing 🏎
      script: cd seshat; make; cd ../web; bundle install; bundle exec rake
